In [1]:
# Start by importing necessary packages
import requests
import pandas as pd
import numpy as np
from IPython.display import display
from io import StringIO

from dstapi import DstApi # The helper class

In [2]:
# Directly embed parameters in the URL with response.get()
requests.get('https://api.statbank.dk/v1' + '/tableinfo' + "?id=metrox1&format=JSON").json()

# Pass a dictionary of parameters to requests.get()
params = {'id': 'NAIO3', 'format': 'JSON'}
requests.get('https://api.statbank.dk/v1' + '/tableinfo', params=params).json()

# Use response.post() - note the change in the name of the parameter about the table's name
# I'm also adding here a language parameter - most tables are available in both Danish and English
params = {'table': 'NAIO3', 'format': 'JSON', 'lang':'da'}
requests.post('https://api.statbank.dk/v1' + '/tableinfo', json=params).json()

{'id': 'NAIO3',
 'text': 'Input-output tabel. Primære input fordelt efter anvendelse og prisenhed',
 'description': 'Input-output tabel. Primære input fordelt efter anvendelse og prisenhed efter tilgangstype, anvendelse, prisenhed og tid',
 'unit': 'Mio. kr.',
 'suppressedDataValue': '0',
 'updated': '2025-06-30T08:00:00',
 'active': True,
 'contacts': [{'name': 'Peter Rørmose Jensen',
   'phone': '+4540135126',
   'mail': 'prj@dst.dk'}],
 'documentation': {'id': '3bcd13ae-d587-4f0c-9207-5794646ef3cc',
  'url': 'https://www.dst.dk/statistikdokumentation/3bcd13ae-d587-4f0c-9207-5794646ef3cc'},
 'footnote': None,
 'variables': [{'id': 'TILGANG1',
   'text': 'tilgangstype',
   'elimination': False,
   'time': False,
   'values': [{'id': 'D214X31',
     'text': 'Produktskatter, netto ekskl. told og moms'},
    {'id': 'D211', 'text': 'Moms'},
    {'id': 'D29X39', 'text': 'Andre produktionsskatter, netto'},
    {'id': 'D1', 'text': 'Aflønning af ansatte'},
    {'id': 'B2A3G',
     'text': 'Bruttooverskud af produktion og blandet indkomst'},
    {'id': 'PRIMINP', 'text': 'Primære input, i alt'}]},
  {'id': 'ANVENDELSE',
   'text': 'anvendelse',
   'elimination': False,
   'time': False,
   'values': [{'id': 'AA00000', 'text': 'Anvendelse, i alt-(Anvendelse)'},
    {'id': 'AI00000', 'text': 'Forbrug i produktionen, i alt-(Anvendelse)'},
    {'id': 'AA', 'text': 'A Landbrug, skovbrug og fiskeri- (Anvendelse)'},
    {'id': 'A01000', 'text': '01000 Landbrug og gartneri- (Anvendelse)'},
    {'id': 'A010000', 'text': '010000 Landbrug og gartneri- (Anvendelse)'},
    {'id': 'A02000', 'text': '02000 Skovbrug- (Anvendelse)'},
    {'id': 'A020000', 'text': '020000 Skovbrug- (Anvendelse)'},
    {'id': 'A03000', 'text': '03000 Fiskeri- (Anvendelse)'},
    {'id': 'A030000', 'text': '030000 Fiskeri- (Anvendelse)'},
    {'id': 'AB', 'text': 'B Råstofindvinding- (Anvendelse)'},
    {'id': 'A06090', 'text': '06090 Råstofindvinding- (Anvendelse)'},
    {'id': 'A060000',
     'text': '060000 Indvinding af olie og gas- (Anvendelse)'},
    {'id': 'A080090',
     'text': '080090 Indvinding af grus og sten- (Anvendelse)'},
    {'id': 'A090000',
     'text': '090000 Service til råstofindvinding- (Anvendelse)'},
    {'id': 'AC', 'text': 'C Industri- (Anvendelse)'},
    {'id': 'ACA',
     'text': 'CA Føde-, drikke- og tobaksvareindustri- (Anvendelse)'},
    {'id': 'A10120',
     'text': '10120 Føde-, drikke- og tobaksvareindustri- (Anvendelse)'},
    {'id': 'A100010', 'text': '100010 Slagterier- (Anvendelse)'},
    {'id': 'A100020', 'text': '100020 Fiskeindustri- (Anvendelse)'},
    {'id': 'A100030', 'text': '100030 Mejerier- (Anvendelse)'},
    {'id': 'A100040',
     'text': '100040 Bagerier, brødfabrikker mv.- (Anvendelse)'},
    {'id': 'A100050', 'text': '100050 Anden fødevareindustri- (Anvendelse)'},
    {'id': 'A110000', 'text': '110000 Drikkevareindustri- (Anvendelse)'},
    {'id': 'A120000', 'text': '120000 Tobaksindustri- (Anvendelse)'},
    {'id': 'ACB', 'text': 'CB Tekstil- og læderindustri- (Anvendelse)'},
    {'id': 'A13150', 'text': '13150 Tekstil- og læderindustri- (Anvendelse)'},
    {'id': 'A130000', 'text': '130000 Tekstilindustri- (Anvendelse)'},
    {'id': 'A140000', 'text': '140000 Beklædningsindustri- (Anvendelse)'},
    {'id': 'A150000',
     'text': '150000 Læder- og fodtøjsindustri- (Anvendelse)'},
    {'id': 'ACC',
     'text': 'CC Træ- og papirindustri, trykkerier- (Anvendelse)'},
    {'id': 'A16000', 'text': '16000 Træindustri- (Anvendelse)'},
    {'id': 'A160000', 'text': '160000 Træindustri- (Anvendelse)'},
    {'id': 'A17000', 'text': '17000 Papirindustri- (Anvendelse)'},
    {'id': 'A170000', 'text': '170000 Papirindustri- (Anvendelse)'},
    {'id': 'A18000', 'text': '18000 Trykkerier mv.- (Anvendelse)'},
    {'id': 'A180000', 'text': '180000 Trykkerier mv.- (Anvendelse)'},
    {'id': 'ACD', 'text': 'CD Olieraffinaderier mv.- (Anvendelse)'},
    {'id': 'A19000', 'text': '19000 Olieraffinaderier mv.- (Anvendelse)'},
    {'id': 'A190000', 'text': '190000 Olieraffinaderier mv.- (Anvendelse)'},
    {'id': 'ACE', 'text': 'CE Kemisk industri- (Anvendelse)'},
    {'id': 'A20000', 'text': '20000 Kemisk industri- (Anvendelse)'},
    {'id': 'A200010',
     'text': '200010 Fremst. af basiskemikalier- (Anvendelse)'},
    {'id': 'A200020',
     'text': '200020 Fremst. af maling og sæbe mv.- (Anvendelse)'},
    {'id': 'ACF', 'text': 'CF Medicinalindustri- (Anvendelse)'},
    {'id': 'A21000', 'text': '21000 Medicinalindustri- (Anvendelse)'},
    {'id': 'A210000', 'text': '210000 Medicinalindustri- (Anvendelse)'},
    {'id': 'ACG', 'text': 'CG Plast-, glas- og betonindustri- (Anvendelse)'},
    {'id': 'A22000', 'text': '22000 Plast- og gummiindustri- (Anvendelse)'},
    {'id': 'A220000', 'text': '220000 Plast- og gummiindustri- (Anvendelse)'},
    {'id': 'A23000', 'text': '23000 Glas- og betonindustri- (Anvendelse)'},
    {'id': 'A230010',
     'text': '230010 Glasindustri og keramisk industri- (Anvendelse)'},
    {'id': 'A230020',
     'text': '230020 Betonindustri og teglværker- (Anvendelse)'},
    {'id': 'ACH', 'text': 'CH Metalindustri- (Anvendelse)'},
    {'id': 'A24000', 'text': '24000 Fremst. af metal- (Anvendelse)'},
    {'id': 'A240000', 'text': '240000 Fremst. af metal- (Anvendelse)'},
    {'id': 'A25000', 'text': '25000 Metalvareindustri- (Anvendelse)'},
    {'id': 'A250000', 'text': '250000 Metalvareindustri- (Anvendelse)'},
    {'id': 'ACI', 'text': 'CI Elektronikindustri- (Anvendelse)'},
    {'id': 'A26000', 'text': '26000 Elektronikindustri- (Anvendelse)'},
    {'id': 'A260010',
     'text': '260010 Fremst. af computere og kommunikationsudstyr mv.- (Anvendelse)'},
    {'id': 'A260020',
     'text': '260020 Fremst. af andet elektronisk udstyr- (Anvendelse)'},
    {'id': 'ACJ', 'text': 'CJ Fremst. af elektrisk udstyr- (Anvendelse)'},
    {'id': 'A27000',
     'text': '27000 Fremst. af elektrisk udstyr- (Anvendelse)'},
    {'id': 'A270010',
     'text': '270010 Fremst. af elektriske motorer mv.- (Anvendelse)'},
    {'id': 'A270020',
     'text': '270020 Fremst. af ledninger og kabler- (Anvendelse)'},
    {'id': 'A270030',
     'text': '270030 Fremst. af husholdningsapparater, lamper mv.- (Anvendelse)'},
    {'id': 'ACK', 'text': 'CK Maskinindustri- (Anvendelse)'},
    {'id': 'A28000', 'text': '28000 Maskinindustri- (Anvendelse)'},
    {'id': 'A280010',
     'text': '280010 Fremst. af motorer, vindmøller og pumper- (Anvendelse)'},
    {'id': 'A280020',
     'text': '280020 Fremst. af andre maskiner- (Anvendelse)'},
    {'id': 'ACL', 'text': 'CL Transportmiddelindustri- (Anvendelse)'},
    {'id': 'A29000',
     'text': '29000 Fremst. af motorkøretøjer og dele hertil- (Anvendelse)'},
    {'id': 'A290000',
     'text': '290000 Fremst. af motorkøretøjer og dele hertil- (Anvendelse)'},
    {'id': 'A30000',
     'text': '30000 Fremst. af skibe og andre transportmidler- (Anvendelse)'},
    {'id': 'A300000',
     'text': '300000 Fremst. af skibe og andre transportmidler- (Anvendelse)'},
    {'id': 'ACM', 'text': 'CM Møbel- og anden industri mv.- (Anvendelse)'},
    {'id': 'A31320', 'text': '31320 Møbel- og anden industri- (Anvendelse)'},
    {'id': 'A310000', 'text': '310000 Møbelindustri- (Anvendelse)'},
    {'id': 'A320010',
     'text': '320010 Fremst. af medicinske instrumenter mv.- (Anvendelse)'},
    {'id': 'A320020',
     'text': '320020 Legetøj og anden fremstillingsvirksomhed- (Anvendelse)'},
    {'id': 'A33000',
     'text': '33000 Reparation og installation af maskiner og udstyr- (Anvendelse)'},
    {'id': 'A330000',
     'text': '330000 Reparation og installation af maskiner og udstyr- (Anvendelse)'},
    {'id': 'AD_E', 'text': 'D_E Forsyningsvirksomhed- (Anvendelse)'},
    {'id': 'AD', 'text': 'D Energiforsyning- (Anvendelse)'},
    {'id': 'A35000', 'text': '35000 Energiforsyning- (Anvendelse)'},
    {'id': 'A350010', 'text': '350010 Elforsyning- (Anvendelse)'},
    {'id': 'A350020', 'text': '350020 Gasforsyning- (Anvendelse)'},
    {'id': 'A350030', 'text': '350030 Varmeforsyning- (Anvendelse)'},
    {'id': 'AE', 'text': 'E Vandforsyning og renovation- (Anvendelse)'},
    {'id': 'A36000', 'text': '36000 Vandforsyning- (Anvendelse)'},
    {'id': 'A360000', 'text': '360000 Vandforsyning- (Anvendelse)'},
    {'id': 'A37390',
     'text': '37390 Renovation, affaldsbehandling mv.- (Anvendelse)'},
    {'id': 'A370000', 'text': '370000 Kloak- og rensningsanlæg- (Anvendelse)'},
    {'id': 'A383900',
     'text': '383900 Renovation, genbrug og forureningsbekæmpelse- (Anvendelse)'},
    {'id': 'AF', 'text': 'F Bygge og anlæg- (Anvendelse)'},
    {'id': 'A41430', 'text': '41430 Bygge og anlæg- (Anvendelse)'},
    {'id': 'A410009', 'text': '410009 Nybyggeri- (Anvendelse)'},
    {'id': 'A420000', 'text': '420000 Anlægsvirksomhed- (Anvendelse)'},
    {'id': 'A430003',
     'text': '430003 Professionel reparation og vedligeholdelse af bygninger- (Anvendelse)'},
    {'id': 'A430004',
     'text': '430004 Gør-det-selv reparation og vedligeholdelse af boliger- (Anvendelse)'},
    {'id': 'AG_I', 'text': 'G_I Handel og transport mv.- (Anvendelse)'},
    {'id': 'AG', 'text': 'G Handel- (Anvendelse)'},
    {'id': 'A45000',
     'text': '45000 Bilhandel og -værksteder mv.- (Anvendelse)'},
    {'id': 'A450010', 'text': '450010 Bilhandel- (Anvendelse)'},
    {'id': 'A450020', 'text': '450020 Bilværksteder mv.- (Anvendelse)'},
    {'id': 'A46000', 'text': '46000 Engroshandel- (Anvendelse)'},
    {'id': 'A460000', 'text': '460000 Engroshandel- (Anvendelse)'},
    {'id': 'A47000', 'text': '47000 Detailhandel- (Anvendelse)'},
    {'id': 'A470000', 'text': '470000 Detailhandel- (Anvendelse)'},
    {'id': 'AH', 'text': 'H Transport- (Anvendelse)'},
    {'id': 'A49000', 'text': '49000 Landtransport- (Anvendelse)'},
    {'id': 'A490010', 'text': '490010 Regional- og fjerntog- (Anvendelse)'},
    {'id': 'A490020',
     'text': '490020 Lokaltog, bus og taxi mv.- (Anvendelse)'},
    {'id': 'A490030',
     'text': '490030 Fragtvognmænd og rørtransport- (Anvendelse)'},
    {'id': 'A50000', 'text': '50000 Skibsfart- (Anvendelse)'},
    {'id': 'A500000', 'text': '500000 Skibsfart- (Anvendelse)'},
    {'id': 'A51000', 'text': '51000 Luftfart- (Anvendelse)'},
    {'id': 'A510000', 'text': '510000 Luftfart- (Anvendelse)'},
    {'id': 'A52000',
     'text': '52000 Hjælpevirksomhed til transport- (Anvendelse)'},
    {'id': 'A520000',
     'text': '520000 Hjælpevirksomhed til transport- (Anvendelse)'},
    {'id': 'A53000', 'text': '53000 Post og kurertjeneste- (Anvendelse)'},
    {'id': 'A530000', 'text': '530000 Post og kurertjeneste- (Anvendelse)'},
    {'id': 'AI', 'text': 'I Hoteller og restauranter- (Anvendelse)'},
    {'id': 'A55560', 'text': '55560 Hoteller og restauranter- (Anvendelse)'},
    {'id': 'A550000', 'text': '550000 Hoteller mv.- (Anvendelse)'},
    {'id': 'A560000', 'text': '560000 Restauranter- (Anvendelse)'},
    {'id': 'AJ', 'text': 'J Information og kommunikation- (Anvendelse)'},
    {'id': 'AJA', 'text': 'JA Forlag, tv og radio- (Anvendelse)'},
    {'id': 'A58000', 'text': '58000 Udgivervirksomhed- (Anvendelse)'},
    {'id': 'A580010', 'text': '580010 Forlag- (Anvendelse)'},
    {'id': 'A580020',
     'text': '580020 Udgivelse af computerspil og anden software- (Anvendelse)'},
    {'id': 'A59600',
     'text': '59600 Radio- og tv-stationer samt produktion af film, tv, mus- (Anvendelse)'},
    {'id': 'A590000',
     'text': '590000 Produktion af film, tv og musik mv.- (Anvendelse)'},
    {'id': 'A600000', 'text': '600000 Radio- og tv-stationer- (Anvendelse)'},
    {'id': 'AJB', 'text': 'JB Telekommunikation- (Anvendelse)'},
    {'id': 'A61000', 'text': '61000 Telekommunikation- (Anvendelse)'},
    {'id': 'A610000', 'text': '610000 Telekommunikation- (Anvendelse)'},
    {'id': 'AJC', 'text': 'JC It- og informationstjenester- (Anvendelse)'},
    {'id': 'A62630',
     'text': '62630 It- og informationstjenester- (Anvendelse)'},
    {'id': 'A620000', 'text': '620000 It-konsulenter mv.- (Anvendelse)'},
    {'id': 'A630000', 'text': '630000 Informationstjenester- (Anvendelse)'},
    {'id': 'AK', 'text': 'K Finansiering og forsikring- (Anvendelse)'},
    {'id': 'A64000', 'text': '64000 Finansiel virksomhed- (Anvendelse)'},
    {'id': 'A640010', 'text': '640010 Pengeinstitutter- (Anvendelse)'},
    {'id': 'A640020', 'text': '640020 Kreditforeninger mv.- (Anvendelse)'},
    {'id': 'A65000', 'text': '65000 Forsikring og pension- (Anvendelse)'},
    {'id': 'A650000', 'text': '650000 Forsikring og pension- (Anvendelse)'},
    {'id': 'A66000', 'text': '66000 Finansiel service- (Anvendelse)'},
    {'id': 'A660000', 'text': '660000 Finansiel service- (Anvendelse)'},
    {'id': 'ALA',
     'text': 'LA Ejendomshandel og udlejning af erhvervsejendomme- (Anvendelse)'},
    {'id': 'A68100', 'text': '68100 Ejendomsmæglere mv.- (Anvendelse)'},
    {'id': 'A680010', 'text': '680010 Ejendomsmæglere mv.- (Anvendelse)'},
    {'id': 'A68300',
     'text': '68300 Udlejning af erhvervsejendomme- (Anvendelse)'},
    {'id': 'A680030',
     'text': '680030 Udlejning af erhvervsejendomme- (Anvendelse)'},
    {'id': 'ALB', 'text': 'LB Boliger- (Anvendelse)'},
    {'id': 'A68203',
     'text': '68203 Boliger, husleje i lejeboliger- (Anvendelse)'},
    {'id': 'A680023',
     'text': '680023 Boliger, husleje i lejeboliger- (Anvendelse)'},
    {'id': 'A68204', 'text': '68204 Boliger, ejerboliger mv.- (Anvendelse)'},
    {'id': 'A680024', 'text': '680024 Boliger, ejerboliger mv.- (Anvendelse)'},
    {'id': 'AM_N', 'text': 'M_N Erhvervsservice- (Anvendelse)'},
    {'id': 'AM', 'text': 'M Videnservice- (Anvendelse)'},
    {'id': 'AMA', 'text': 'MA Rådgivning mv.- (Anvendelse)'},
    {'id': 'A69700',
     'text': '69700 Advokater, revisorer og virksomhedskonsulenter- (Anvendelse)'},
    {'id': 'A690010', 'text': '690010 Advokatvirksomhed- (Anvendelse)'},
    {'id': 'A690020', 'text': '690020 Revision og bogføring- (Anvendelse)'},
    {'id': 'A700000', 'text': '700000 Virksomhedskonsulenter- (Anvendelse)'},
    {'id': 'A71000',
     'text': '71000 Arkitekter og rådgivende ingeniører- (Anvendelse)'},
    {'id': 'A710000',
     'text': '710000 Arkitekter og rådgivende ingeniører- (Anvendelse)'},
    {'id': 'AMB', 'text': 'MB Forskning og udvikling- (Anvendelse)'},
    {'id': 'A72001',
     'text': '72001 Forskning og udvikling, markedsmæssig- (Anvendelse)'},
    {'id': 'A720001',
     'text': '720001 Forskning og udvikling, markedsmæssig- (Anvendelse)'},
    {'id': 'A72002',
     'text': '72002 Forskning og udvikling, ikke-markedsmæssig- (Anvendelse)'},
    {'id': 'A720002',
     'text': '720002 Forskning og udvikling, ikke-markedsmæssig- (Anvendelse)'},
    {'id': 'AMC',
     'text': 'MC Reklame og øvrige erhvervsservice- (Anvendelse)'},
    {'id': 'A73000',
     'text': '73000 Reklame- og analysebureauer- (Anvendelse)'},
    {'id': 'A730000',
     'text': '730000 Reklame- og analysebureauer- (Anvendelse)'},
    {'id': 'A74750',
     'text': '74750 Dyrlæger og anden videnservice- (Anvendelse)'},
    {'id': 'A740000', 'text': '740000 Anden videnservice- (Anvendelse)'},
    {'id': 'A750000', 'text': '750000 Dyrlæger- (Anvendelse)'},
    {'id': 'AN',
     'text': 'N Rejsebureauer, rengøring og anden operationel service- (Anvendelse)'},
    {'id': 'A77000',
     'text': '77000 Udlejning og leasing af materiel- (Anvendelse)'},
    {'id': 'A770000',
     'text': '770000 Udlejning og leasing af materiel- (Anvendelse)'},
    {'id': 'A78000',
     'text': '78000 Arbejdsformidling og vikarbureauer- (Anvendelse)'},
    {'id': 'A780000',
     'text': '780000 Arbejdsformidling og vikarbureauer- (Anvendelse)'},
    {'id': 'A79000', 'text': '79000 Rejsebureauer- (Anvendelse)'},
    {'id': 'A790000', 'text': '790000 Rejsebureauer- (Anvendelse)'},
    {'id': 'A80820',
     'text': '80820 Rengøring og anden operationel service- (Anvendelse)'},
    {'id': 'A800000',
     'text': '800000 Vagt og sikkerhedstjeneste- (Anvendelse)'},
    {'id': 'A810000',
     'text': '810000 Ejendomsservice, rengøring og anlægsgartnere- (Anvendelse)'},
    {'id': 'A820000',
     'text': '820000 Anden operationel service- (Anvendelse)'},
    {'id': 'AO_Q',
     'text': 'O_Q Offentlig administration, undervisning og sundhed- (Anvendelse)'},
    {'id': 'AO',
     'text': 'O Offentlig administration, forsvar og politi- (Anvendelse)'},
    {'id': 'A84202',
     'text': '84202 Offentlig administration mv.- (Anvendelse)'},
    {'id': 'A840010', 'text': '840010 Offentlig administration- (Anvendelse)'},
    {'id': 'A840022',
     'text': '840022 Forsvar, politi og retsvæsen mv., ikke-markedsmæssig- (Anvendelse)'},
    {'id': 'A84101',
     'text': '84101 Redningskorps mv., markedsmæssig- (Anvendelse)'},
    {'id': 'A840021',
     'text': '840021 Redningskorps mv., markedsmæssig- (Anvendelse)'},
    {'id': 'AP', 'text': 'P Undervisning- (Anvendelse)'},
    {'id': 'A85202',
     'text': '85202 Undervisning, ikke-markedsmæssig- (Anvendelse)'},
    {'id': 'A850010', 'text': '850010 Grundskoler- (Anvendelse)'},
    {'id': 'A850020',
     'text': '850020 Gymnasier og erhvervsfaglige skoler- (Anvendelse)'},
    {'id': 'A850030',
     'text': '850030 Videregående uddannelsesinstitutioner- (Anvendelse)'},
    {'id': 'A850042',
     'text': '850042 Voksenundervisning mv., ikke-markedsmæssig- (Anvendelse)'},
    {'id': 'A85101',
     'text': '85101 Voksenundervisning mv., markedsmæssig- (Anvendelse)'},
    {'id': 'A850041',
     'text': '850041 Voksenundervisning mv., markedsmæssig- (Anvendelse)'},
    {'id': 'AQ', 'text': 'Q Sundhed og socialvæsen- (Anvendelse)'},
    {'id': 'AQA', 'text': 'QA Sundhedsvæsen- (Anvendelse)'},
    {'id': 'A86000', 'text': '86000 Sundhedsvæsen- (Anvendelse)'},
    {'id': 'A860010', 'text': '860010 Hospitaler- (Anvendelse)'},
    {'id': 'A860020', 'text': '860020 Læger, tandlæger mv.- (Anvendelse)'},
    {'id': 'AQB', 'text': 'QB Sociale institutioner- (Anvendelse)'},
    {'id': 'A87880', 'text': '87880 Sociale institutioner- (Anvendelse)'},
    {'id': 'A870000', 'text': '870000 Plejehjem mv.- (Anvendelse)'},
    {'id': 'A880000',
     'text': '880000 Daginstitutioner og dagcentre mv.- (Anvendelse)'},
    {'id': 'AR_S',
     'text': 'R_S Kultur, fritid og anden service- (Anvendelse)'},
    {'id': 'AR', 'text': 'R Kultur og fritid- (Anvendelse)'},
    {'id': 'A90920', 'text': '90920 Kunst, kultur og spil- (Anvendelse)'},
    {'id': 'A900000', 'text': '900000 Teater, musik og kunst- (Anvendelse)'},
    {'id': 'A910001',
     'text': '910001 Biblioteker, museer mv., markedsmæssig- (Anvendelse)'},
    {'id': 'A910002',
     'text': '910002 Biblioteker, museer mv., ikke-markedsmæssig- (Anvendelse)'},
    {'id': 'A920000', 'text': '920000 Lotteri og andet spil- (Anvendelse)'},
    {'id': 'A93000',
     'text': '93000 Sport, forlystelsesparker og andre fritidsaktiviteter- (Anvendelse)'},
    {'id': 'A930011', 'text': '930011 Sport, markedsmæssig- (Anvendelse)'},
    {'id': 'A930012',
     'text': '930012 Sport, ikke-markedsmæssig- (Anvendelse)'},
    {'id': 'A930020',
     'text': '930020 Forlystelsesparker og andre fritidsaktiviteter- (Anvendelse)'},
    {'id': 'ASA', 'text': 'SA Andre serviceydelser- (Anvendelse)'},
    {'id': 'A94000',
     'text': '94000 Organisationer og foreninger- (Anvendelse)'},
    {'id': 'A940000',
     'text': '940000 Organisationer og foreninger- (Anvendelse)'},
    {'id': 'A95000',
     'text': '95000 Reparation af husholdningsudstyr- (Anvendelse)'},
    {'id': 'A950000',
     'text': '950000 Reparation af husholdningsudstyr- (Anvendelse)'},
    {'id': 'A96000',
     'text': '96000 Frisører, vaskerier og andre serviceydelser- (Anvendelse)'},
    {'id': 'A960000',
     'text': '960000 Frisører, vaskerier og andre serviceydelser- (Anvendelse)'},
    {'id': 'ASB',
     'text': 'SB Private husholdninger med ansat medhjælp- (Anvendelse)'},
    {'id': 'A97000',
     'text': '97000 Private husholdninger med ansat medhjælp- (Anvendelse)'},
    {'id': 'A970000',

In [3]:
# Initialize the class with the target table
I_landbrug = DstApi('NAIO3')

# Get the table summary
I_landbrug.tablesummary(language='da')

Table NAIO3: Input-output tabel. Primære input fordelt efter anvendelse og prisenhed efter tilgangstype, anvendelse, prisenhed og tid
Last update: 2025-06-30T08:00:00

,variable name,# values,First value,First value label,Last value,Last value label,Time variable
0,TILGANG1,6,D214X31,"Produktskatter, netto ekskl. told og moms",PRIMINP,"Primære input, i alt",False
1,ANVENDELSE,447,AA00000,"Anvendelse, i alt-(Anvendelse)",AE6000,Eksport - (Anvendelse),False
2,PRISENHED,2,V,Løbende priser,Y,Foregående års priser,False
3,Tid,57,1966,1966,2022,2022,True

In [4]:
levels = I_landbrug.variable_levels('TILGANG1', language='da')
print(levels.to_string(index=False))

     id                                             text
D214X31        Produktskatter, netto ekskl. told og moms
   D211                                             Moms
 D29X39                  Andre produktionsskatter, netto
     D1                             Aflønning af ansatte
  B2A3G Bruttooverskud af produktion og blandet indkomst
PRIMINP                             Primære input, i alt

In [5]:
levels = I_landbrug.variable_levels('ANVENDELSE', language='da')
print(levels.to_string(index=False))

         id                                                                         text
    AA00000                                               Anvendelse, i alt-(Anvendelse)
    AI00000                                   Forbrug i produktionen, i alt-(Anvendelse)
         AA                                A Landbrug, skovbrug og fiskeri- (Anvendelse)
     A01000                                     01000 Landbrug og gartneri- (Anvendelse)
    A010000                                    010000 Landbrug og gartneri- (Anvendelse)
     A02000                                                 02000 Skovbrug- (Anvendelse)
    A020000                                                020000 Skovbrug- (Anvendelse)
     A03000                                                  03000 Fiskeri- (Anvendelse)
    A030000                                                 030000 Fiskeri- (Anvendelse)
         AB                                             B Råstofindvinding- (Anvendelse)
     A06090                                         06090 Råstofindvinding- (Anvendelse)
    A060000                               060000 Indvinding af olie og gas- (Anvendelse)
    A080090                              080090 Indvinding af grus og sten- (Anvendelse)
    A090000                            090000 Service til råstofindvinding- (Anvendelse)
         AC                                                     C Industri- (Anvendelse)
        ACA                        CA Føde-, drikke- og tobaksvareindustri- (Anvendelse)
     A10120                     10120 Føde-, drikke- og tobaksvareindustri- (Anvendelse)
    A100010                                              100010 Slagterier- (Anvendelse)
    A100020                                           100020 Fiskeindustri- (Anvendelse)
    A100030                                                100030 Mejerier- (Anvendelse)
    A100040                             100040 Bagerier, brødfabrikker mv.- (Anvendelse)
    A100050                                  100050 Anden fødevareindustri- (Anvendelse)
    A110000                                      110000 Drikkevareindustri- (Anvendelse)
    A120000                                          120000 Tobaksindustri- (Anvendelse)
        ACB                                   CB Tekstil- og læderindustri- (Anvendelse)
     A13150                                13150 Tekstil- og læderindustri- (Anvendelse)
    A130000                                         130000 Tekstilindustri- (Anvendelse)
    A140000                                     140000 Beklædningsindustri- (Anvendelse)
    A150000                               150000 Læder- og fodtøjsindustri- (Anvendelse)
        ACC                           CC Træ- og papirindustri, trykkerier- (Anvendelse)
     A16000                                              16000 Træindustri- (Anvendelse)
    A160000                                             160000 Træindustri- (Anvendelse)
     A17000                                            17000 Papirindustri- (Anvendelse)
    A170000                                           170000 Papirindustri- (Anvendelse)
     A18000                                           18000 Trykkerier mv.- (Anvendelse)
    A180000                                          180000 Trykkerier mv.- (Anvendelse)
        ACD                                       CD Olieraffinaderier mv.- (Anvendelse)
     A19000                                    19000 Olieraffinaderier mv.- (Anvendelse)
    A190000                                   190000 Olieraffinaderier mv.- (Anvendelse)
        ACE                                             CE Kemisk industri- (Anvendelse)
     A20000                                          20000 Kemisk industri- (Anvendelse)
    A200010                              200010 Fremst. af basiskemikalier- (Anvendelse)
    A200020                           200020 Fremst. af maling og sæbe mv.- (Anvendelse)
        ACF                                           CF Medicinalindustri- (Anvendelse)
     A21000                                        21000 Medicinalindustri- (Anvendelse)
    A210000                                       210000 Medicinalindustri- (Anvendelse)
        ACG                              CG Plast-, glas- og betonindustri- (Anvendelse)
     A22000                                  22000 Plast- og gummiindustri- (Anvendelse)
    A220000                                 220000 Plast- og gummiindustri- (Anvendelse)
     A23000                                   23000 Glas- og betonindustri- (Anvendelse)
    A230010                       230010 Glasindustri og keramisk industri- (Anvendelse)
    A230020                             230020 Betonindustri og teglværker- (Anvendelse)
        ACH                                               CH Metalindustri- (Anvendelse)
     A24000                                         24000 Fremst. af metal- (Anvendelse)
    A240000                                        240000 Fremst. af metal- (Anvendelse)
     A25000                                        25000 Metalvareindustri- (Anvendelse)
    A250000                                       250000 Metalvareindustri- (Anvendelse)
        ACI                                          CI Elektronikindustri- (Anvendelse)
     A26000                                       26000 Elektronikindustri- (Anvendelse)
    A260010        260010 Fremst. af computere og kommunikationsudstyr mv.- (Anvendelse)
    A260020                     260020 Fremst. af andet elektronisk udstyr- (Anvendelse)
        ACJ                                 CJ Fremst. af elektrisk udstyr- (Anvendelse)
     A27000                              27000 Fremst. af elektrisk udstyr- (Anvendelse)
    A270010                       270010 Fremst. af elektriske motorer mv.- (Anvendelse)
    A270020                          270020 Fremst. af ledninger og kabler- (Anvendelse)
    A270030            270030 Fremst. af husholdningsapparater, lamper mv.- (Anvendelse)
        ACK                                              CK Maskinindustri- (Anvendelse)
     A28000                                           28000 Maskinindustri- (Anvendelse)
    A280010                280010 Fremst. af motorer, vindmøller og pumper- (Anvendelse)
    A280020                               280020 Fremst. af andre maskiner- (Anvendelse)
        ACL                                     CL Transportmiddelindustri- (Anvendelse)
     A29000                 29000 Fremst. af motorkøretøjer og dele hertil- (Anvendelse)
    A290000                290000 Fremst. af motorkøretøjer og dele hertil- (Anvendelse)
     A30000                30000 Fremst. af skibe og andre transportmidler- (Anvendelse)
    A300000               300000 Fremst. af skibe og andre transportmidler- (Anvendelse)
        ACM                                CM Møbel- og anden industri mv.- (Anvendelse)
     A31320                                 31320 Møbel- og anden industri- (Anvendelse)
    A310000                                           310000 Møbelindustri- (Anvendelse)
    A320010                  320010 Fremst. af medicinske instrumenter mv.- (Anvendelse)
    A320020                320020 Legetøj og anden fremstillingsvirksomhed- (Anvendelse)
     A33000         33000 Reparation og installation af maskiner og udstyr- (Anvendelse)
    A330000        330000 Reparation og installation af maskiner og udstyr- (Anvendelse)
       AD_E                                       D_E Forsyningsvirksomhed- (Anvendelse)
         AD                                              D Energiforsyning- (Anvendelse)
     A35000                                          35000 Energiforsyning- (Anvendelse)
    A350010                                             350010 Elforsyning- (Anvendelse)
    A350020                                            350020 Gasforsyning- (Anvendelse)
    A350030                                          350030 Varmeforsyning- (Anvendelse)
         AE                                  E Vandforsyning og renovation- (Anvendelse)
     A36000                                            36000 Vandforsyning- (Anvendelse)
    A360000                                           360000 Vandforsyning- (Anvendelse)
     A37390                        37390 Renovation, affaldsbehandling mv.- (Anvendelse)
    A370000                                370000 Kloak- og rensningsanlæg- (Anvendelse)
    A383900            383900 Renovation, genbrug og forureningsbekæmpelse- (Anvendelse)
         AF                                               F Bygge og anlæg- (Anvendelse)
     A41430                                           41430 Bygge og anlæg- (Anvendelse)
    A410009                                               410009 Nybyggeri- (Anvendelse)
    A420000                                        420000 Anlægsvirksomhed- (Anvendelse)
    A430003 430003 Professionel reparation og vedligeholdelse af bygninger- (Anvendelse)
    A430004   430004 Gør-det-selv reparation og vedligeholdelse af boliger- (Anvendelse)
       AG_I                                    G_I Handel og transport mv.- (Anvendelse)
         AG                                                       G Handel- (Anvendelse)
     A45000                             45000 Bilhandel og -værksteder mv.- (Anvendelse)
    A450010                                               450010 Bilhandel- (Anvendelse)
    A450020                                       450020 Bilværksteder mv.- (Anvendelse)
     A46000                                             46000 Engroshandel- (Anvendelse)
    A460000                                            460000 Engroshandel- (Anvendelse)
     A47000                                             47000 Detailhandel- (Anvendelse)
    A470000                                            470000 Detailhandel- (Anvendelse)
         AH                                                    H Transport- (Anvendelse)
     A49000                                            49000 Landtransport- (Anvendelse)
    A490010                                   490010 Regional- og fjerntog- (Anvendelse)
    A490020                               490020 Lokaltog, bus og taxi mv.- (Anvendelse)
    A490030                           490030 Fragtvognmænd og rørtransport- (Anvendelse)
     A50000                                                50000 Skibsfart- (Anvendelse)
    A500000                                               500000 Skibsfart- (Anvendelse)
     A51000                                                 51000 Luftfart- (Anvendelse)
    A510000                                                510000 Luftfart- (Anvendelse)
     A52000                           52000 Hjælpevirksomhed til transport- (Anvendelse)
    A520000                          520000 Hjælpevirksomhed til transport- (Anvendelse)
     A53000                                    53000 Post og kurertjeneste- (Anvendelse)
    A530000                                   530000 Post og kurertjeneste- (Anvendelse)
         AI                                     I Hoteller og restauranter- (Anvendelse)
     A55560                                 55560 Hoteller og restauranter- (Anvendelse)
    A550000                                            550000 Hoteller mv.- (Anvendelse)
    A560000                                            560000 Restauranter- (Anvendelse)
         AJ                                 J Information og kommunikation- (Anvendelse)
        AJA                                         JA Forlag, tv og radio- (Anvendelse)
     A58000                                        58000 Udgivervirksomhed- (Anvendelse)
    A580010                                                  580010 Forlag- (Anvendelse)
    A580020             580020 Udgivelse af computerspil og anden software- (Anvendelse)
     A59600  59600 Radio- og tv-stationer samt produktion af film, tv, mus- (Anvendelse)
    A590000                     590000 Produktion af film, tv og musik mv.- (Anvendelse)
    A600000                                  600000 Radio- og tv-stationer- (Anvendelse)
        AJB                                           JB Telekommunikation- (Anvendelse)
     A61000                                        61000 Telekommunikation- (Anvendelse)
    A610000                                       610000 Telekommunikation- (Anvendelse)
        AJC                                JC It- og informationstjenester- (Anvendelse)
     A62630                             62630 It- og informationstjenester- (Anvendelse)
    A620000                                      620000 It-konsulenter mv.- (Anvendelse)
    A630000                                   630000 Informationstjenester- (Anvendelse)
         AK                                   K Finansiering og forsikring- (Anvendelse)
     A64000                                     64000 Finansiel virksomhed- (Anvendelse)
    A640010                                        640010 Pengeinstitutter- (Anvendelse)
    A640020                                    640020 Kreditforeninger mv.- (Anvendelse)
     A65000                                    65000 Forsikring og pension- (Anvendelse)
    A650000                                   650000 Forsikring og pension- (Anvendelse)
     A66000                                        66000 Finansiel service- (Anvendelse)
    A660000                                       660000 Finansiel service- (Anvendelse)
        ALA            LA Ejendomshandel og udlejning af erhvervsejendomme- (Anvendelse)
     A68100                                      68100 Ejendomsmæglere mv.- (Anvendelse)
    A680010                                     680010 Ejendomsmæglere mv.- (Anvendelse)
     A68300                           68300 Udlejning af erhvervsejendomme- (Anvendelse)
    A680030                          680030 Udlejning af erhvervsejendomme- (Anvendelse)
        ALB                                                     LB Boliger- (Anvendelse)
     A68203                           68203 Boliger, husleje i lejeboliger- (Anvendelse)
    A680023                          680023 Boliger, husleje i lejeboliger- (Anvendelse)
     A68204                                 68204 Boliger, ejerboliger mv.- (Anvendelse)
    A680024                                680024 Boliger, ejerboliger mv.- (Anvendelse)
       AM_N                                            M_N Erhvervsservice- (Anvendelse)
         AM                                                 M Videnservice- (Anvendelse)
        AMA                                              MA Rådgivning mv.- (Anvendelse)
     A69700           69700 Advokater, revisorer og virksomhedskonsulenter- (Anvendelse)
    A690010                                       690010 Advokatvirksomhed- (Anvendelse)
    A690020                                   690020 Revision og bogføring- (Anvendelse)
    A700000                                  700000 Virksomhedskonsulenter- (Anvendelse)
     A71000                      71000 Arkitekter og rådgivende ingeniører- (Anvendelse)
    A710000                     710000 Arkitekter og rådgivende ingeniører- (Anvendelse)
        AMB                                      MB Forskning og udvikling- (Anvendelse)
     A72001                    72001 Forskning og udvikling, markedsmæssig- (Anvendelse)
    A720001                   720001 Forskning og udvikling, markedsmæssig- (Anvendelse)
     A72002               72002 Forskning og udvikling, ikke-markedsmæssig- (Anvendelse)
    A720002              720002 Forskning og udvikling, ikke-markedsmæssig- (Anvendelse)
        AMC                           MC Reklame og øvrige erhvervsservice- (Anvendelse)
     A73000                              73000 Reklame- og analysebureauer- (Anvendelse)
    A730000                             730000 Reklame- og analysebureauer- (Anvendelse)
     A74750                           74750 Dyrlæger og anden videnservice- (Anvendelse)
    A740000                                      740000 Anden videnservice- (Anvendelse)
    A750000                                                750000 Dyrlæger- (Anvendelse)
         AN        N Rejsebureauer, rengøring og anden operationel service- (Anvendelse)
     A77000                         77000 Udlejning og leasing af materiel- (Anvendelse)
    A770000                        770000 Udlejning og leasing af materiel- (Anvendelse)
     A78000                       78000 Arbejdsformidling og vikarbureauer- (Anvendelse)
    A780000                      780000 Arbejdsformidling og vikarbureauer- (Anvendelse)
     A79000                                            79000 Rejsebureauer- (Anvendelse)
    A790000                                           790000 Rejsebureauer- (Anvendelse)
     A80820                   80820 Rengøring og anden operationel service- (Anvendelse)
    A800000                              800000 Vagt og sikkerhedstjeneste- (Anvendelse)
    A810000            810000 Ejendomsservice, rengøring og anlægsgartnere- (Anvendelse)
    A820000                               820000 Anden operationel service- (Anvendelse)
       AO_Q          O_Q Offentlig administration, undervisning og sundhed- (Anvendelse)
         AO                  O Offentlig administration, forsvar og politi- (Anvendelse)
     A84202                             84202 Offentlig administration mv.- (Anvendelse)
    A840010                                840010 Offentlig administration- (Anvendelse)
    A840022    840022 Forsvar, politi og retsvæsen mv., ikke-markedsmæssig- (Anvendelse)
     A84101                         84101 Redningskorps mv., markedsmæssig- (Anvendelse)
    A840021                        840021 Redningskorps mv., markedsmæssig- (Anvendelse)
         AP                                                 P Undervisning- (Anvendelse)
     A85202                         85202 Undervisning, ikke-markedsmæssig- (Anvendelse)
    A850010                                             850010 Grundskoler- (Anvendelse)
    A850020                     850020 Gymnasier og erhvervsfaglige skoler- (Anvendelse)
    A850030                   850030 Videregående uddannelsesinstitutioner- (Anvendelse)
    A850042              850042 Voksenundervisning mv., ikke-markedsmæssig- (Anvendelse)
     A85101                    85101 Voksenundervisning mv., markedsmæssig- (Anvendelse)
    A850041                   850041 Voksenundervisning mv., markedsmæssig- (Anvendelse)
         AQ                                       Q Sundhed og socialvæsen- (Anvendelse)
        AQA                                               QA Sundhedsvæsen- (Anvendelse)
     A86000                                            86000 Sundhedsvæsen- (Anvendelse)
    A860010                                              860010 Hospitaler- (Anvendelse)
    A860020                                    860020 Læger, tandlæger mv.- (Anvendelse)
        AQB                                       QB Sociale institutioner- (Anvendelse)
     A87880                                    87880 Sociale institutioner- (Anvendelse)
    A870000                                           870000 Plejehjem mv.- (Anvendelse)
    A880000                       880000 Daginstitutioner og dagcentre mv.- (Anvendelse)
       AR_S                            R_S Kultur, fritid og anden service- (Anvendelse)
         AR                                             R Kultur og fritid- (Anvendelse)
     A90920                                    90920 Kunst, kultur og spil- (Anvendelse)
    A900000                                  900000 Teater, musik og kunst- (Anvendelse)
    A910001                  910001 Biblioteker, museer mv., markedsmæssig- (Anvendelse)
    A910002             910002 Biblioteker, museer mv., ikke-markedsmæssig- (Anvendelse)
    A920000                                   920000 Lotteri og andet spil- (Anvendelse)
     A93000    93000 Sport, forlystelsesparker og andre fritidsaktiviteter- (Anvendelse)
    A930011                                    930011 Sport, markedsmæssig- (Anvendelse)

In [6]:
params = {
    'table': 'NAIO3',
    'format': 'BULK',
    'variables': [
        {'code': 'TILGANG1', 'values': [
    "D214X31",  # Produktskatter, netto ekskl. told og moms
    "D211",     # Moms
    "D29X39",    # Andre produktionsskatter, netto
    "D1"         # Aflønning af ansatte
]},
        {'code': 'ANVENDELSE', 'values': [
    "A01000",  # 010000 Landbrug og gartneri-(Anvendelse)
    "A020000",  # 020000 Skovbrug-(Anvendelse)
    "A030000",  # 030000 Fiskeri-(Anvendelse)
    "AB",       # B Råstofindvinding-(Anvendelse)
    "A10120",  # 10120 Føde-, drikke- og tobaksvareindustri-(Anvendelse)
    "ACB",      # CB Tekstil- og læderindustri-(Anvendelse)
    "ACC",      # CC Træ- og papirindustri, trykkerier-(Anvendelse)
    "ACD",      # CD Olieraffinaderier mv.-(Anvendelse)
    "ACE",      # CE Kemisk industri-(Anvendelse)
    "ACF",      # CF Medicinalindustri-(Anvendelse)
    "ACG",      # CG Plast-, glas- og betonindustri-(Anvendelse)
    "ACH",      # CH Metalindustri-(Anvendelse)
    "ACI",      # CI Elektronikindustri-(Anvendelse)
    "ACJ",      # CJ Fremst. af elektrisk udstyr-(Anvendelse)
    "ACK",      # CK Maskinindustri-(Anvendelse)
    "ACL",      # CL Transportmiddelindustri-(Anvendelse)
    "ACM",      # CM Møbel- og anden industri mv.-(Anvendelse)
    "AD_E",     # D_E Forsyningsvirksomhed-(Anvendelse)
    "AF",       # F Bygge og anlæg-(Anvendelse)
    "AG_I",     # G_I Handel og transport mv.-(Anvendelse)
    "AJ",       # J Information og kommunikation-(Anvendelse)
    "AK",       # K Finansiering og forsikring-(Anvendelse)
    "ALA",      # LA Ejendomshandel og udlejning af erhvervsejendomme-(Anvendelse)
    "ALB",      # LB Boliger-(Anvendelse)
    "AM_N",     # M_N Erhvervsservice-(Anvendelse)
    "AO_Q",     # O_Q Offentlig administration, undervisning og sundhed-(Anvendelse)
    "AR_S",     # R_S Kultur, fritid og anden service-(Anvendelse)
]
},
        {'code': 'PRISENHED', 'values': ['*']},
        {'code': 'TID', 'values': ['*']}
    ]
}
r = requests.post('https://api.statbank.dk/v1' + '/data', json=params)
print(r.text[:200])

TILGANG1;ANVENDELSE;PRISENHED;TID;INDHOLD
Andre produktionsskatter, netto;B Råstofindvinding- (Anvendelse);Løbende priser;1998;-22,866
Andre produktionsskatter, netto;B Råstofindvinding- (Anvendelse

In [7]:
df = pd.read_csv(
    StringIO(
        requests.post('https://api.statbank.dk/v1' + '/data', json=params).text
    ), sep=';'
)

# Behandler og summer over data

## Tilgang

In [8]:
# 1) Sørg for at INDHOLD er tal (DK-format: komma som decimal)
df["INDHOLD"] = (
    df["INDHOLD"].astype(str)
      .str.replace("\u00a0", "", regex=False)  # non-breaking space
      .str.replace(" ", "", regex=False)       # mellemrum som tusindtals-sep
      .str.replace(".", "", regex=False)       # punktum som tusindtals-sep (hvis findes)
      .str.replace(",", ".", regex=False)      # komma -> punktum (decimal)
)
df["INDHOLD"] = pd.to_numeric(df["INDHOLD"], errors="coerce")

## Anvendelse

### Alt andet

In [9]:
# Brancher der skal trækkes fra (1-4)
exclude_codes = [
    "01000 Landbrug og gartneri- (Anvendelse)",
    "10120 Føde-, drikke- og tobaksvareindustri- (Anvendelse)"
]

# Dit nye id/navn for "resten"
new_name = "REST_ANVENDELSE"  # unikt id
new_id   = "REST_ANVENDELSE Øvrige brancher"

# Gruppér på alle andre dimensioner end TILGANG2 og INDHOLD
group_cols = [c for c in df.columns if c not in ["ANVENDELSE", "INDHOLD"]]

# Sum over alle brancher i tilgang, men udelad de fem ovenfor
new_rows = (
    df.loc[~df["ANVENDELSE"].isin(exclude_codes)]
      .groupby(group_cols, as_index=False)["INDHOLD"]
      .sum()
)

# Sæt den nye kode og tilføj tilbage
new_rows["ANVENDELSE"] = new_id
df = pd.concat([df, new_rows[df.columns]], ignore_index=True)

In [10]:
print("Antal REST-rækker:", (df["ANVENDELSE"] == new_id).sum())
print(df.loc[df["ANVENDELSE"] == new_id, ["TILGANG1","TID","PRISENHED","INDHOLD"]].head(200).to_string(index=False))

Antal REST-rækker: 452
                       TILGANG1  TID             PRISENHED     INDHOLD
           Aflønning af ansatte 1967 Foregående års priser       0.000
           Aflønning af ansatte 1968 Foregående års priser       0.000
           Aflønning af ansatte 1969 Foregående års priser       0.000
           Aflønning af ansatte 1970 Foregående års priser       0.000
           Aflønning af ansatte 1971 Foregående års priser       0.000
           Aflønning af ansatte 1972 Foregående års priser       0.000
           Aflønning af ansatte 1973 Foregående års priser       0.000
           Aflønning af ansatte 1974 Foregående års priser       0.000
           Aflønning af ansatte 1975 Foregående års priser       0.000
           Aflønning af ansatte 1976 Foregående års priser       0.000
           Aflønning af ansatte 1977 Foregående års priser       0.000
           Aflønning af ansatte 1978 Foregående års priser       0.000
           Aflønning af ansatte 1979 Foregående års priser       0.000
           Aflønning af ansatte 1980 Foregående års priser       0.000
           Aflønning af ansatte 1981 Foregående års priser       0.000
           Aflønning af ansatte 1982 Foregående års priser       0.000
           Aflønning af ansatte 1983 Foregående års priser       0.000
           Aflønning af ansatte 1984 Foregående års priser       0.000
           Aflønning af ansatte 1985 Foregående års priser       0.000
           Aflønning af ansatte 1986 Foregående års priser       0.000
           Aflønning af ansatte 1987 Foregående års priser       0.000
           Aflønning af ansatte 1988 Foregående års priser       0.000
           Aflønning af ansatte 1989 Foregående års priser       0.000
           Aflønning af ansatte 1990 Foregående års priser       0.000
           Aflønning af ansatte 1991 Foregående års priser       0.000
           Aflønning af ansatte 1992 Foregående års priser       0.000
           Aflønning af ansatte 1993 Foregående års priser       0.000
           Aflønning af ansatte 1994 Foregående års priser       0.000
           Aflønning af ansatte 1995 Foregående års priser       0.000
           Aflønning af ansatte 1996 Foregående års priser       0.000
           Aflønning af ansatte 1997 Foregående års priser       0.000
           Aflønning af ansatte 1998 Foregående års priser       0.000
           Aflønning af ansatte 1999 Foregående års priser       0.000
           Aflønning af ansatte 2000 Foregående års priser       0.000
           Aflønning af ansatte 2001 Foregående års priser       0.000
           Aflønning af ansatte 2002 Foregående års priser       0.000
           Aflønning af ansatte 2003 Foregående års priser       0.000
           Aflønning af ansatte 2004 Foregående års priser       0.000
           Aflønning af ansatte 2005 Foregående års priser       0.000
           Aflønning af ansatte 2006 Foregående års priser       0.000
           Aflønning af ansatte 2007 Foregående års priser       0.000
           Aflønning af ansatte 2008 Foregående års priser       0.000
           Aflønning af ansatte 2009 Foregående års priser       0.000
           Aflønning af ansatte 2010 Foregående års priser       0.000
           Aflønning af ansatte 2011 Foregående års priser       0.000
           Aflønning af ansatte 2012 Foregående års priser       0.000
           Aflønning af ansatte 2013 Foregående års priser       0.000
           Aflønning af ansatte 2014 Foregående års priser       0.000
           Aflønning af ansatte 2015 Foregående års priser       0.000
           Aflønning af ansatte 2016 Foregående års priser       0.000
           Aflønning af ansatte 2017 Foregående års priser       0.000
           Aflønning af ansatte 2018 Foregående års priser       0.000
           Aflønning af ansatte 2019 Foregående års priser       0.000
           Aflønning af ansatte 2020 Foregående års priser       0.000
           Aflønning af ansatte 2021 Foregående års priser       0.000
           Aflønning af ansatte 2022 Foregående års priser       0.000
           Aflønning af ansatte 1966        Løbende priser   37662.585
           Aflønning af ansatte 1967        Løbende priser   42113.253
           Aflønning af ansatte 1968        Løbende priser   47085.698
           Aflønning af ansatte 1969        Løbende priser   53941.137
           Aflønning af ansatte 1970        Løbende priser   61298.167
           Aflønning af ansatte 1971        Løbende priser   69366.057
           Aflønning af ansatte 1972        Løbende priser   77106.532
           Aflønning af ansatte 1973        Løbende priser   88417.880
           Aflønning af ansatte 1974        Løbende priser  103904.376
           Aflønning af ansatte 1975        Løbende priser  116921.070
           Aflønning af ansatte 1976        Løbende priser  134057.440
           Aflønning af ansatte 1977        Løbende priser  148464.885
           Aflønning af ansatte 1978        Løbende priser  164677.525
           Aflønning af ansatte 1979        Løbende priser  184011.931
           Aflønning af ansatte 1980        Løbende priser  202867.774
           Aflønning af ansatte 1981        Løbende priser  218940.720
           Aflønning af ansatte 1982        Løbende priser  248798.026
           Aflønning af ansatte 1983        Løbende priser  271820.964
           Aflønning af ansatte 1984        Løbende priser  293456.299
           Aflønning af ansatte 1985        Løbende priser  317781.194
           Aflønning af ansatte 1986        Løbende priser  342687.785
           Aflønning af ansatte 1987        Løbende priser  373955.369
           Aflønning af ansatte 1988        Løbende priser  394626.050
           Aflønning af ansatte 1989        Løbende priser  411932.184
           Aflønning af ansatte 1990        Løbende priser  429525.195
           Aflønning af ansatte 1991        Løbende priser  443491.649
           Aflønning af ansatte 1992        Løbende priser  456410.585
           Aflønning af ansatte 1993        Løbende priser  459439.789
           Aflønning af ansatte 1994        Løbende priser  475046.036
           Aflønning af ansatte 1995        Løbende priser  496743.096
           Aflønning af ansatte 1996        Løbende priser  523893.365
           Aflønning af ansatte 1997        Løbende priser  550014.056
           Aflønning af ansatte 1998        Løbende priser  582022.907
           Aflønning af ansatte 1999        Løbende priser  612265.587
           Aflønning af ansatte 2000        Løbende priser  637795.140
           Aflønning af ansatte 2001        Løbende priser  671595.798
           Aflønning af ansatte 2002        Løbende priser  695601.521
           Aflønning af ansatte 2003        Løbende priser  714065.451
           Aflønning af ansatte 2004        Løbende priser  735966.632
           Aflønning af ansatte 2005        Løbende priser  773330.681
           Aflønning af ansatte 2006        Løbende priser  821043.114
           Aflønning af ansatte 2007        Løbende priser  874545.350
           Aflønning af ansatte 2008        Løbende priser  921843.803
           Aflønning af ansatte 2009        Løbende priser  918598.012
           Aflønning af ansatte 2010        Løbende priser  926364.441
           Aflønning af ansatte 2011        Løbende priser  939961.900
           Aflønning af ansatte 2012        Løbende priser  951026.978
           Aflønning af ansatte 2013        Løbende priser  967936.653
           Aflønning af ansatte 2014        Løbende priser  989402.381
           Aflønning af ansatte 2015        Løbende priser 1020398.614
           Aflønning af ansatte 2016        Løbende priser 1053285.018
           Aflønning af ansatte 2017        Løbende priser 1087111.882
           Aflønning af ansatte 2018        Løbende priser 1124998.842
           Aflønning af ansatte 2019        Løbende priser 1163144.088
           Aflønning af ansatte 2020        Løbende priser 1178056.495
           Aflønning af ansatte 2021        Løbende priser 1245661.908
           Aflønning af ansatte 2022        Løbende priser 1333027.881
Andre produktionsskatter, netto 1967 Foregående års priser       0.000
Andre produktionsskatter, netto 1968 Foregående års priser       0.000
Andre produktionsskatter, netto 1969 Foregående års priser       0.000
Andre produktionsskatter, netto 1970 Foregående års priser       0.000
Andre produktionsskatter, netto 1971 Foregående års priser       0.000
Andre produktionsskatter, netto 1972 Foregående års priser       0.000
Andre produktionsskatter, netto 1973 Foregående års priser       0.000
Andre produktionsskatter, netto 1974 Foregående års priser       0.000
Andre produktionsskatter, netto 1975 Foregående års priser       0.000
Andre produktionsskatter, netto 1976 Foregående års priser       0.000
Andre produktionsskatter, netto 1977 Foregående års priser       0.000
Andre produktionsskatter, netto 1978 Foregående års priser       0.000
Andre produktionsskatter, netto 1979 Foregående års priser       0.000
Andre produktionsskatter, netto 1980 Foregående års priser       0.000
Andre produktionsskatter, netto 1981 Foregående års priser       0.000
Andre produktionsskatter, netto 1982 Foregående års priser       0.000
Andre produktionsskatter, netto 1983 Foregående års priser       0.000
Andre produktionsskatter, netto 1984 Foregående års priser       0.000
Andre produktionsskatter, netto 1985 Foregående års priser       0.000
Andre produktionsskatter, netto 1986 Foregående års priser       0.000
Andre produktionsskatter, netto 1987 Foregående års priser       0.000
Andre produktionsskatter, netto 1988 Foregående års priser       0.000
Andre produktionsskatter, netto 1989 Foregående års priser       0.000
Andre produktionsskatter, netto 1990 Foregående års priser       0.000
Andre produktionsskatter, netto 1991 Foregående års priser       0.000
Andre produktionsskatter, netto 1992 Foregående års priser       0.000
Andre produktionsskatter, netto 1993 Foregående års priser       0.000
Andre produktionsskatter, netto 1994 Foregående års priser       0.000
Andre produktionsskatter, netto 1995 Foregående års priser       0.000
Andre produktionsskatter, netto 1996 Foregående års priser       0.000
Andre produktionsskatter, netto 1997 Foregående års priser       0.000
Andre produktionsskatter, netto 1998 Foregående års priser       0.000
Andre produktionsskatter, netto 1999 Foregående års priser       0.000
Andre produktionsskatter, netto 2000 Foregående års priser       0.000
Andre produktionsskatter, netto 2001 Foregående års priser       0.000
Andre produktionsskatter, netto 2002 Foregående års priser       0.000
Andre produktionsskatter, netto 2003 Foregående års priser       0.000
Andre produktionsskatter, netto 2004 Foregående års priser       0.000
Andre produktionsskatter, netto 2005 Foregående års priser       0.000
Andre produktionsskatter, netto 2006 Foregående års priser       0.000
Andre produktionsskatter, netto 2007 Foregående års priser       0.000
Andre produktionsskatter, netto 2008 Foregående års priser       0.000
Andre produktionsskatter, netto 2009 Foregående års priser       0.000
Andre produktionsskatter, netto 2010 Foregående års priser       0.000
Andre produktionsskatter, netto 2011 Foregående års priser       0.000
Andre produktionsskatter, netto 2012 Foregående års priser       0.000
Andre produktionsskatter, netto 2013 Foregående års priser       0.000
Andre produktionsskatter, netto 2014 Foregående års priser       0.000
Andre produktionsskatter, netto 2015 Foregående års priser       0.000
Andre produktionsskatter, netto 2016 Foregående års priser       0.000
Andre produktionsskatter, netto 2017 Foregående års priser       0.000
Andre produktionsskatter, netto 2018 Foregående års priser       0.000
Andre produktionsskatter, netto 2019 Foregående års priser       0.000
Andre produktionsskatter, netto 2020 Foregående års priser       0.000
Andre produktionsskatter, netto 2021 Foregående års priser       0.000
Andre produktionsskatter, netto 2022 Foregående års priser       0.000
Andre produktionsskatter, netto 1966        Løbende priser    1045.979
Andre produktionsskatter, netto 1967        Løbende priser    1146.175
Andre produktionsskatter, netto 1968        Løbende priser    1225.886
Andre produktionsskatter, netto 1969        Løbende priser    1262.836
Andre produktionsskatter, netto 1970        Løbende priser    1672.184
Andre produktionsskatter, netto 1971        Løbende priser    1940.362
Andre produktionsskatter, netto 1972        Løbende priser    1925.766
Andre produktionsskatter, netto 1973        Løbende priser    2119.521
Andre produktionsskatter, netto 1974        Løbende priser     896.498
Andre produktionsskatter, netto 1975        Løbende priser    2602.648
Andre produktionsskatter, netto 1976        Løbende priser    1870.315
Andre produktionsskatter, netto 1977        Løbende priser    2358.753
Andre produktionsskatter, netto 1978        Løbende priser    3135.848
Andre produktionsskatter, netto 1979        Løbende priser    3277.524
Andre produktionsskatter, netto 1980        Løbende priser    3314.121
Andre produktionsskatter, netto 1981        Løbende priser    2755.992
Andre produktionsskatter, netto 1982        Løbende priser    1626.878
Andre produktionsskatter, netto 1983        Løbende priser     246.075
Andre produktionsskatter, netto 1984        Løbende priser     314.404
Andre produktionsskatter, netto 1985        Løbende priser     917.634
Andre produktionsskatter, netto 1986        Løbende priser    1946.376
Andre produktionsskatter, netto 1987        Løbende priser    4472.062
Andre produktionsskatter, netto 1988        Løbende priser    1588.444
Andre produktionsskatter, netto 1989        Løbende priser    -163.774
Andre produktionsskatter, netto 1990        Løbende priser   -1184.074
Andre produktionsskatter, netto 1991        Løbende priser    -235.766
Andre produktionsskatter, netto 1992        Løbende priser   -4168.124
Andre produktionsskatter, netto 1993        Løbende priser    1263.545
Andre produktionsskatter, netto 1994        Løbende priser    1419.387
Andre produktionsskatter, netto 1995        Løbende priser     381.427
Andre produktionsskatter, netto 1996        Løbende priser    -772.449

# Gem udvalgt data

In [11]:
# 1. Vælg de kategorier du vil beholde

udvalgte_anvendelse = [
    "01000 Landbrug og gartneri- (Anvendelse)",
    "10120 Føde-, drikke- og tobaksvareindustri- (Anvendelse)",
    "REST_ANVENDELSE Øvrige brancher",
]

# 2. Lav det nye datasæt ved at filtrere
# Vi tjekker om TILGANG2 er i vores liste OG om ANVENDELSE er i vores liste
df_subset = df[(df["ANVENDELSE"].isin(udvalgte_anvendelse))
].copy()

# 3. Tjek resultatet
print(f"Det nye datasæt har {df_subset.shape[0]} rækker.")
display(df_subset.head())
df_subset.to_csv('Data69/input_landbrugsdata.csv', index=False)

Det nye datasæt har 1356 rækker.

,TILGANG1,ANVENDELSE,PRISENHED,TID,INDHOLD
46,"Andre produktionsskatter, netto",01000 Landbrug og gartneri- (Anvendelse),Løbende priser,1998,-754.36
47,"Andre produktionsskatter, netto",01000 Landbrug og gartneri- (Anvendelse),Foregående års priser,1998,NaN
52,"Andre produktionsskatter, netto","10120 Føde-, drikke- og tobaksvareindustri- (A...",Løbende priser,1998,-136.37
53,"Andre produktionsskatter, netto","10120 Føde-, drikke- og tobaksvareindustri- (A...",Foregående års priser,1998,NaN
100,Aflønning af ansatte,01000 Landbrug og gartneri- (Anvendelse),Løbende priser,2002,5285.78